project:
  type: book
  output-dir: docs

book:
  title: "Estatística Básica: conceitos e aplicações no R"
  author: "Henrique José de Paula Alves"
  date: "04/15/2026"
  #cover-image: cover.png
  downloads: [pdf, epub]
  
  chapters:
    - index.qmd
    - preface.qmd
    #- summary.qmd
    - part: "Capítulos"
      numbered: true
      chapters:
        - introducao.qmd
        - cap2.qmd
    - part: final.qmd
      chapters:
        - consfinais.qmd
        - references.qmd
        
  sidebar:
     pinned: true
    
  search: 
    location: sidebar
    type: textbox



# bibliography: references.bib

format:
  html:
    css: styles.css
    theme: 
      light: theme-dark.scss
      dark: cosmo
  # pdf:
  #   documentclass: book
  #   keep-md: true
  #   keep-tex: true
  #   code-copy: true
  #   toc: true                # Sugestão: Adiciona sumário, comum em livros (Krantz)
  #   number-sections: true    # Sugestão: Numeração de seções para documentos técnicos
  #   

engine: knitr   
    

editor: visual

